# Generated by Django 3.1.2 on 2020-10-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201001_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='carNumber',
            field=models.CharField(help_text='Enter the car number', max_length=10),
        ),
    ]
