# Generated by Django 3.1.2 on 2020-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201002_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetail',
            name='carNumber',
            field=models.CharField(help_text='Enter the car number', max_length=10),
        ),
    ]
