# Generated by Django 3.1.2 on 2020-10-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201002_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetail',
            name='slotNumber',
            field=models.IntegerField(help_text='enter slot num', unique=True),
        ),
    ]
