# Generated by Django 3.1.2 on 2020-10-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNumber', models.CharField(max_length=200)),
                ('status', models.CharField(default='parked', max_length=15)),
                ('cerated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotNumber', models.IntegerField(unique=True)),
                ('status', models.CharField(default='empty', max_length=15)),
                ('cerated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('carNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkApp.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='slotNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkApp.parking'),
        ),
    ]
